version: '3'

services:
  cassandra:
    container_name: cassandra_db
    image: cassandra:latest
    ports:
      - 9042:9042
    environment:
      - MAX_HEAP_SIZE=256M
      - HEAP_NEWSIZE=128M
    volumes:
      - ./cassandra:/var/lib/cassandra