version: '3'
services:
  jupyter-lab:
    image: jupyterlab:python-3.10.6-jdk-11.10.16
    container_name: jupyter-lab
    ports:
      - 8888:8888
    volumes:
      - ./workspace/jupyterlab:/opt/jupyterlab
      - ./jupyterlab/config:/root/.jupyter