version: '3'
services:

  postgres:
    image: postgres:latest
    container_name: postgres-database
    ports:
      - 5432:5432
    volumes:
      - ./workspace/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    networks:
      - big-data

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    restart: unless-stopped
    networks:
      - big-data

  # pgadmin:
  #   container_name: pgadmin_container
  #   image: dpage/pgadmin4
  #   environment:

  #   ports:
  #     - 5050:80
  #   networks:
  #     - big-data

networks:
  big-data:
    external: true