version: "3"
services:
  redis:
    image: redis:latest
    container_name: superset_cache
    restart: unless-stopped
    volumes:
      - redis:/data
  
  db:
    image: postgres:10
    container_name: superset_db
    restart: unless-stopped
    env_file: superset.env
    volumes:
      - db_home:/var/lib/postgresql/data

  superset:
    image: apache/superset:latest-dev
    container_name: superset
    command: ["/app/docker/docker-bootstrap.sh", "app-gunicorn"]
    restart: unless-stopped
    ports:
      - 8088:8088
    env_file: superset.env
    depends_on:
      - db
      - redis
    volumes:
      - ./superset/docker:/app/docker
      - superset_home:/app/superset_home

  superset-init:
    image: apache/superset:latest-dev
    container_name: superset_init
    command: ["/app/docker/docker-init.sh"]
    env_file: superset.env
    depends_on:
      - db
      - redis
    user: "root"
    volumes:
      - ./superset/docker:/app/docker
      - superset_home:/app/superset_home
    healthcheck:
      disable: true

  superset-worker:
    image: apache/superset:latest-dev
    container_name: superset_worker
    command: ["/app/docker/docker-bootstrap.sh", "worker"]
    env_file: superset.env
    restart: unless-stopped
    env_file: superset.env
    depends_on:
      - db
      - redis
    user: "root"
    volumes:
      - ./superset/docker:/app/docker
      - superset_home:/app/superset_home
    healthcheck:
      test: ["CMD-SHELL", "celery inspect ping -A superset.tasks.celery_app:app -d celery@$$HOSTNAME"]

  superset-worker-beat:
    image: apache/superset:latest-dev
    container_name: superset_worker_beat
    command: ["/app/docker/docker-bootstrap.sh", "beat"]
    env_file: superset.env
    restart: unless-stopped
    depends_on:
      - db
      - redis
    user: "root"
    volumes:
      - ./superset/docker:/app/docker
      - superset_home:/app/superset_home
    healthcheck:
      disable: true

volumes:
  superset_home:
    external: false
  db_home:
    external: false
  redis:
    external: false
