version: '3'

services:
  airflow_master:
    image: airflow:python-3.10.6-jdk-11.10.16
    ports:
      - 8080:8080
    volumes:
      - ./dags:/airflow/dags
      - ./plugins:/airflow/plugins
      - ./logs:/airflow/logs
      - ./config/airflow_master.cfg:/airflow/airflow.cfg
    env_file:
      - environments/airflow_master.env
    healthcheck:
      test: ["CMD-SHELL", "[ -f /airflow/airflow-webserver.pid ]"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s