version: '3'
services:
  redis-master:
    container_name: "redis-master"
    image: redis:latest
    command: redis-server
    ports:
      - 6379:6379

  redis-slave1: 
    container_name: "redis-slave1"
    image: redis:latest
    ports:
      - 6380:6379
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  redis-slave2: 
    container_name: "redis-slave2"
    image: redis:latest
    ports:
      - 6381:6379
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master 